version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"